### ISSUE TITLE
Primary secondary code laten zien

### ISSUE THREAD

**Issue by driezie** [Naddybs/look-and-feel-living-styleguide#2]
### Issue die ik vond
https://github.com/Naddybs/look-and-feel-living-styleguide/blob/a424b6ab5091057f0313b1c4303cdf53e2be0cd5/index.html#L71-L88

Bij dit voorbeeld is het niet super duidelijk wat de kleuren zijn. Hiervoor kan je dit beter laten zien door het volgende te doen

### Hoe je het beste kan laten zien:
```css
:root {
    --primary-color: #fff;
    --secondary-color: #fff;
    --tertiary-color: #fff;

    --active: #fff;
    ---disabled: #fff;

    --action-color-1: #fff;
    --action-color-2: #fff;
    --action-color-3: #fff;
    --action-color-4: #fff;
}
```

voor meer informatie over :root bekijk [hier](https://developer.mozilla.org/en-US/docs/Web/CSS/:root)

`PS: dit kan je in een code tag plaatsen zodat je dit op de pagina ziet`
